version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "80:8000"
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            - db
            # - redis

    redis:
        image: redis:7-alpine

    celery_worker:
        restart: always
        build:
            context: .
        command: celery worker --app=core.celery.app --loglevel=info
        volumes:
            - .:/code
        env_file:
            - ./.env.dev

        depends_on:
            - redis
            - db
            - web

    celery_beat:
        build:
            context: .
        command: celery -A core.celery beat
        volumes:
            - .:/code
        env_file:
            - ./.env.dev
        depends_on:
            - redis
            - db
            - web
