version: "3"
services:
    web:
        build:
            context: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code

        ports:
            - 8000:8000
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=app
            - DB_USER=appuser
            - DB_PASSWORD=ashish@23
            - DEBUG=True
            - SECRET_KEY='django-insecure-a1g)1du+@6h$c+u8hcpw9(r#7wjj%y0t)vy=9dju7@313le07s'
    db:
        image: postgres
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=appuser
            - POSTGRES_PASSWORD=ashish@23
