# Generated by Django 3.2 on 2021-12-30 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('min_order', models.IntegerField()),
                ('max_order', models.IntegerField()),
                ('rate', models.IntegerField(help_text='Per 1000 ')),
                ('average_time_hours', models.IntegerField(blank=True, null=True)),
                ('average_time_minutes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('service_id', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.categorymodel')),
            ],
        ),
    ]
