# Generated by Django 3.2 on 2021-12-31 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='servicesmodel',
            options={'verbose_name': 'Service'},
        ),
    ]
