# Generated by Django 3.2 on 2022-01-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicesmodel_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='rate',
            field=models.FloatField(help_text='Per 1000 '),
        ),
    ]
