# Generated by Django 3.2 on 2022-01-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_messagemodel_ticketsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={'verbose_name': 'Message'},
        ),
        migrations.AlterModelOptions(
            name='ticketsmodel',
            options={'verbose_name': 'Ticket'},
        ),
    ]
