# Generated by Django 3.2 on 2022-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_categorymodel_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='blow_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='blow_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='is_refill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='snakers_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='snakers_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
