# Generated by Django 3.2 on 2022-01-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_servicesmodel_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesmodel',
            name='blow_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicesmodel',
            name='snakers_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
