# Generated by Django 3.2 on 2022-02-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20220124_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesmodel',
            old_name='blow_active',
            new_name='sasta_active',
        ),
        migrations.RenameField(
            model_name='servicesmodel',
            old_name='blow_id',
            new_name='sasta_id',
        ),
    ]
