# Generated by Django 3.2 on 2022-02-10 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_auto_20220203_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'ordering': ('ranking',), 'verbose_name': 'Categorie'},
        ),
    ]
