# Generated by Django 3.2 on 2022-02-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_api'),
        ('services', '0012_alter_categorymodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='sasta_active',
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='sasta_id',
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='snakers_active',
        ),
        migrations.RemoveField(
            model_name='servicesmodel',
            name='snakers_id',
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.api'),
        ),
    ]
