# Generated by Django 3.2 on 2022-02-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20220220_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='service_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
