# Generated by Django 3.2.9 on 2022-09-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_offers_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='ranking',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
