# Generated by Django 3.2.9 on 2022-11-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_servicesmodel_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='refill_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
