# Generated by Django 3.2.9 on 2023-01-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_servicesmodel_refill_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
