# Generated by Django 3.2.1 on 2023-07-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_servicesmodel_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesmodel',
            name='last_update',
        ),
    ]
