# Generated by Django 3.2 on 2022-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='blow_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='blow_api',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_headline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='sneaker_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='sneaker_api',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
