# Generated by Django 3.2 on 2022-02-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_settings_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='blow_active',
            new_name='sasta_active',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='blow_api',
            new_name='sasta_id',
        ),
    ]
