# Generated by Django 3.2 on 2022-02-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220203_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='whatsapp_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
