# Generated by Django 3.2 on 2022-02-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_settings_whatsapp_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('api_url', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
