# Generated by Django 3.2 on 2022-02-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='sasta_active',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sasta_id',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sneaker_active',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='sneaker_api',
        ),
    ]
