# Generated by Django 3.2 on 2022-02-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20220222_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='site_headline',
            new_name='keyword',
        ),
        migrations.AddField(
            model_name='settings',
            name='decription',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='favicon',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='settings',
            name='pyament_qr',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='settings',
            name='site_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
