# Generated by Django 3.2 on 2022-02-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220228_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
