# Generated by Django 3.2 on 2022-02-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_decription_settings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='site_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
