# Generated by Django 3.2 on 2022-02-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_settings_whatsapp_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='favicon',
        ),
    ]
