# Generated by Django 3.2.1 on 2022-09-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20220610_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='video_height',
            field=models.IntegerField(default=0, help_text='Youtube Video Height'),
        ),
        migrations.AddField(
            model_name='settings',
            name='video_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='settings',
            name='video_width',
            field=models.IntegerField(default=0, help_text='Youtube Video Width'),
        ),
        migrations.AddField(
            model_name='settings',
            name='youtube_video_link',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
