# Generated by Django 3.2 on 2022-08-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20220610_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='provider_balance',
            field=models.FloatField(default=0),
        ),
    ]
