# Generated by Django 3.2.1 on 2022-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20220905_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='video_height',
            field=models.CharField(default='', help_text='Youtube Video Height', max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='video_width',
            field=models.CharField(default='', help_text='Youtube Video Width', max_length=100),
        ),
    ]
