# Generated by Django 3.2.9 on 2022-09-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_tutorials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorials',
            options={'verbose_name': 'Tutorial'},
        ),
    ]
