# Generated by Django 3.2.9 on 2022-11-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20221104_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='promotional_link',
            field=models.URLField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
