# Generated by Django 3.2.1 on 2023-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_settings_promotional_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='hero_title',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='settings',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='seo_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
