# Generated by Django 3.2 on 2022-01-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_money'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Money',
            new_name='AccountBalance',
        ),
    ]
