# Generated by Django 3.2 on 2022-01-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_rename_money_accountbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='money',
            field=models.FloatField(default=0.0),
        ),
    ]
