# Generated by Django 3.2 on 2022-02-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_accountbalance_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
