# Generated by Django 3.2 on 2022-02-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
