# Generated by Django 3.2.1 on 2023-08-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_create_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
