# Generated by Django 3.2 on 2022-01-07 17:40

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0004_alter_servicesmodel_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Partial', 'Partial'), ('In progress', 'In progress')], default='Pending', max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('charge', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order_placed', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='services.servicesmodel')),
            ],
        ),
    ]
