# Generated by Django 3.2 on 2022-01-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_transanctionsmodel_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transanctionsmodel',
            name='amount',
            field=models.FloatField(),
        ),
    ]
