# Generated by Django 3.2 on 2022-01-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_transanctionsmodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Partial', 'Partial'), ('In progress', 'In progress'), ('Test', 'Test')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transanctionsmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled'), ('Not Valid', 'Not Valid'), ('Test', 'Test')], default='Pending', max_length=20),
        ),
    ]
