# Generated by Django 3.2 on 2022-01-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20220123_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='third_party_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='third_party_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
