# Generated by Django 3.2 on 2022-02-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20220222_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersmodel',
            old_name='remaining',
            new_name='remains',
        ),
    ]
