# Generated by Django 3.2.9 on 2022-11-02 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0016_ordersmodel_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Partial', 'Partial'), ('In progress', 'In progress')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='RefilOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Processing', 'Processing'), ('Cancelled', 'Cancelled'), ('Partial', 'Partial'), ('In progress', 'In progress'), ('Rejected', 'Rejected')], max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordersmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refill Order',
            },
        ),
    ]
