# Generated by Django 3.2.9 on 2022-11-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20221103_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refilorders',
            name='user',
        ),
    ]
