# Generated by Django 3.2.9 on 2022-11-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_refilorders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refilorders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('In progress', 'In progress'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
