# Generated by Django 3.2.9 on 2022-11-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_refilorders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refilorders',
            name='third_party_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
