# Generated by Django 3.2.9 on 2022-11-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_refilorders_third_party_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='refill',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='refill_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersmodel',
            name='refilling',
            field=models.BooleanField(default=False),
        ),
    ]
