# Generated by Django 3.2.1 on 2023-08-09 12:17

from django.db import migrations, models
from django.db.migrations.operations import RunSQL


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20221104_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='refill_days',
        ),
    ]
