# Generated by Django 3.2.1 on 2023-08-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20230809_1747'),
    ]

    operations = [

    ]
