# Generated by Django 3.2.1 on 2023-08-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_ordersmodel_refill_days'),
    ]

    operations = [
    ]
