# Generated by Django 3.2.1 on 2023-08-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_ordersmodel_refill_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='refill_days',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='refill',
            field=models.BooleanField(default=False),
        ),
    ]
